apiVersion: v1
kind: Service
metadata:
  labels:
    run: shortener-go
  name: shortener-go
spec:
  ports:
  - nodePort: 32661
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: shortener-go
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
