apiVersion: v1
kind: Service
metadata:
  labels:
    run: shortener-frontend
  name: shortener-frontend
spec:
  ports:
  - nodePort: 30022
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: shortener-frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
